networks:
  redis-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

services:
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - 12000:12000
      - 8443:8443
      - 9443:9443
    profiles: ['redis']
    networks:
      redis-net:
        ipv4_address: 192.168.20.2

  app:
    build:
      context: .
    environment:
      REDIS_URL: redis://re1:12000
      APP_PORT: 8000
    ports:
      - 8000:8000
    networks:
      redis-net:
        ipv4_address: 192.168.20.3
    profiles: ['app']
